# build_binary:
#     builder: 'particle photon'
#     binary_name: 'firmware/target/firmware.bin'
#     script: cd $SPN_BUILDER_SDK && make PLATFORM=photon APPDIR=$SPN_PROJECT_DIR/firmware
#
testing:
   script: testing/2.simple-tests/send-network-cmd-to-toggle-pin.py
   env_vars:
       - $IFTTT_API_KEY
       - $SPN_PARTICLE_TOKEN
#        ota_method: particle
#        binary: auto
